baseURL = "https://swiss-vital.ch"
languageCode = "de-ch"
title = "SwissVital"
theme = "bootstrap-theme"

[taxonomies]
  category = "categories"
  tag = "tags"
  portfolio = "portfolio"

[params]
  hero_title = "Bleiben Sie gesund"
  hero_subtitle = """Gesund und munter leben: Das wollen wir alle.

Das Wichtigste ist Abwechslung für Körper und Geist, Ernährung mit Augenmass und innere Balance. Und dann kommt: **kluge Vorsorge**.

Wenn Sie hier gelandet sind, weil Sie wissen, dass ein MRT für Sie das Richtige ist, bringt der Button Sie zum Termin. Oder Sie lesen erst noch einmal weiter."""

  about_title = "Wissen macht gesund"
  about_text = """Das Leben ist manchmal unbarmherzig und verlangt uns mehr ab, als der Gesundheit gut tut. Wer seinen Lebenswandel nicht ändern kann, muss besonders gut auf sich achten. Regelmässige, individuell abgestimmte Vorsorge schützt vor bösen Überraschungen und gibt Ihnen das gute Gefühl, auf der sicheren Seite zu sein.

Seit es möglich ist, hochauflösende MRT-Untersuchungen des ganzen Körpers durchzuführen, ist bei der Früherkennung ein neues Zeitalter angebrochen. Vor allem bei Krebserkrankungen haben MRT-Untersuchungen schon tausende Leben gerettet.

Und das ist erst der Anfang."""

  company_name = "SwissVital"
