baseURL = "https://swiss-vital.ch"
languageCode = "de-CH"
title = "SwissVital"
theme = "bootstrap-theme"

defaultContentLanguage = "de"
defaultContentLanguageInSubdir = true

[languages]
  [languages.de]
    languageName = "Deutsch"
    weight = 1
    contentDir = "content/de"
