baseURL = "/"
languageCode = "de-CH"
title = "SwissVital"
theme = "bootstrap-theme"

defaultContentLanguage = "de"
defaultContentLanguageInSubdir = true

# Global parameters for asset processing.
[params]
  enableSourceMaps = true

# Disable minification during development for easier debugging.
[minify]
  disableXML = true
  disableCSS = true
  disableJS = true
  disableHTML = true

[languages]
  [languages.de]
    languageName = "Deutsch"
    weight = 1
    contentDir = "content/de"
    [languages.de.params]
      termin         = "Termin"
      rechtliches    = "Rechtliches"
      standorte      = "Standorte"
      untersuchungen = "Untersuchungen"
      agb            = "AGB"
      datenschutz   = "Datenschutzerklärung"
      impressum      = "Impressum"

  [languages.en]
    languageName = "English"
    weight = 2
    contentDir = "content/en"
    [languages.en.params]
      termin         = "Appointment"
      rechtliches    = "Legal"
      standorte      = "Locations"
      untersuchungen = "Examinations"
      agb            = "Terms and Conditions"
      datenschutz   = "Privacy Policy"
      impressum      = "Imprint"
