[build]
  publish = "public"
  command = "hugo"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/buchung"
  to = "/.netlify/functions/sendConfirmation"
  status = 200
  force = true
