[build]
  publish = "public"
  command = "hugo"

[context.production]
  environment = { HUGO_VERSION = "0.143.1", HUGO_ENV = "production", HUGO_ENABLEGITINFO = "true" }

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/buchung"
  to = "/.netlify/functions/sendConfirmation"
  status = 200
  force = true
